rustgd/cgmath

- src/angle.rs
- src/array.rs
- src/cgmath.rs
- src/matrix.rs
- src/num.rs
- src/point.rs
- src/quaternion.rs
- src/vector.rs
Just fixes the build. Should be a minimal api change.
> Update for associated types changes

- benches/common/macros.rs
- benches/construction.rs
- src/aabb.rs
- src/angle.rs
- src/approx.rs
- src/cgmath.rs
- src/line.rs
- src/matrix.rs
- src/plane.rs
- src/point.rs
- src/projection.rs
- src/quaternion.rs
- src/ray.rs
- src/rotation.rs
- src/transform.rs
- src/vector.rs
- tests/approx.rs
- tests/quaternion.rs
> Updated to latest rustc

- src/vector.rs
It works, and passes all tests.
> Fix for rustc

- src/transform.rs
This fixes the build for me on `rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-20)`.
> Add a phantom type annotation on Transform.

- src/matrix.rs
- src/point.rs
- src/vector.rs
This helps avoid some accidental no-ops.
> Add #[must_use] on functions with in-place variants.

- src/cgmath.rs
- src/transform.rs
- src/vector.rs
- tests/transform.rs
- tests/vector.rs
> ToComponents trait

- Cargo.toml
- src/angle.rs
- src/cgmath.rs
- src/matrix.rs
- src/quaternion.rs
- src/vector.rs
This rolls up #174 and completes #175. It will also should allow for #187 to build.
> Manually implment Rand.

- .travis.yml
- src/angle.rs
- src/lib.rs
- src/rotation.rs
- src/transform.rs
I rebased `rust-1.0` over `master` and this is the result.
The `rust-1.0` branch can be deleted after merging this PR.
Close #213
> Merge the rust-1.0 branch into master

- src/angle.rs
- Allows writing `rad(1) + deg(45)`.
- Allows using `cos`/`sin`/etc. with degrees as well.
> Make functions in angle.rs more generic

- .travis.yml
- Cargo.toml
- README.md
> Use travis-cargo for documentation updates

- src/quaternion.rs
Fixes #224
I haven't really thought about whether there is a faster way to do this, but at least it is fixed.
> Fix Quaternion::mul_self_q

- src/matrix.rs
- src/point.rs
- src/quaternion.rs
- src/transform.rs
- src/vector.rs
> Add some by-value operator overloads

- src/matrix.rs
- src/point.rs
- src/quaternion.rs
- src/rotation.rs
- src/transform.rs
- src/vector.rs
- tests/matrix.rs
- tests/point.rs
- tests/projection.rs
- tests/rotation.rs
- tests/transform.rs
- tests/vector.rs
Working towards #247
cc. @bitshifter
> Make lots of methods take vectors, points, and quaternions by value

- src/matrix.rs
- src/rotation.rs
- src/transform.rs
- tests/matrix.rs
- tests/rotation.rs
> Rename SquareMatrix::one to identity

- src/matrix.rs
> Add matrix scale functions

- CHANGELOG.md
- Cargo.toml
> Add a CHANGELOG, and bump version to 0.6.0

- CHANGELOG.md
- src/transform.rs
- tests/transform.rs
> Remove ToComponents and CompositeTransform traits

- CHANGELOG.md
- src/num.rs
- src/projection.rs
- src/quaternion.rs
These seem to be relics from an older Rust...
> Remove 'static constraints

- CHANGELOG.md
- src/angle.rs
- src/matrix.rs
- src/projection.rs
- src/quaternion.rs
- src/rotation.rs
- src/vector.rs
- tests/angle.rs
> Angle api cleanups

- CHANGELOG.md
- src/angle.rs
- src/macros.rs
- src/matrix.rs
- src/point.rs
- src/quaternion.rs
- src/rotation.rs
- src/transform.rs
- src/vector.rs
- tests/matrix.rs
- tests/projection.rs
> Implement all by-ref/val permutations of matrix operators, and remove operator methods

- src/quaternion.rs
> Make Quaternion::magnitude pass self by-value

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- benches/common/macros.rs
- benches/construction.rs
- benches/mat.rs
- benches/quat.rs
- benches/vec.rs
- src/angle.rs
- src/lib.rs
- src/macros.rs
- src/matrix.rs
- src/point.rs
- src/quaternion.rs
- src/vector.rs
Implements assignment operators, hiding them behind an `"unstable"` feature flag.
Closes #276
> Implement most assignment operators

- README.md
I think this is against the correct repo this time :laughing:
> Fix Travis and License URLs in README.md

- src/matrix.rs
- src/point.rs
- tests/matrix.rs
> Scalar arithmetic operators for Matrix types

- CHANGELOG.md
- src/angle.rs
- src/matrix.rs
- src/point.rs
- src/quaternion.rs
- src/vector.rs
> Mark some types as #[repr(C, packed)]

- CHANGELOG.md
- src/lib.rs
- src/prelude.rs
> Add prelude module for easy importing of common traits

- CHANGELOG.md
- Cargo.toml
- src/conv.rs
- src/lib.rs
I've had these for a while now in my personal project, and thought they might be useful for other people!
> Add constrained conversion functions

- CHANGELOG.md
- benches/vec.rs
- src/array.rs
- src/lib.rs
- src/num.rs
- src/prelude.rs
- src/vector.rs
- tests/vector.rs
> Remove extraneous operator overloads on vectors, and add ElementWise trait

- CHANGELOG.md
- benches/vec.rs
- src/quaternion.rs
- src/vector.rs
- tests/vector.rs
> Rename Vector::length to Vector::magnitude

- CHANGELOG.md
- Cargo.toml
> Un-implicit-glob rustc-serialize version number

- README.md
Re-submitting, after accidentally including another commit
> Add note about column-vector convention

- src/quaternion.rs
Just a simple code reorganisation for clarity.
> Move Quaternion::{slerp, to_euler} out of separate impl block

- CHANGELOG.md
- Cargo.toml
> Update to v0.9.0

- src/angle.rs
Now they are doing something :)
> Fix assignment operators for angles

- Cargo.toml
- src/angle.rs
- src/approx.rs
- src/lib.rs
- src/matrix.rs
- src/num.rs
- src/point.rs
- src/projection.rs
- src/quaternion.rs
- src/structure.rs
- src/transform.rs
- src/vector.rs
> Switch to using num_traits crate from num

- benches/construction.rs
- src/euler.rs
- src/lib.rs
- src/matrix.rs
- src/quaternion.rs
- src/rotation.rs
- tests/matrix.rs
- tests/quaternion.rs
> Switch to an Euler angle type for defining rotations

- src/angle.rs
- src/euler.rs
- src/lib.rs
- src/matrix.rs
- src/point.rs
- src/quaternion.rs
- src/structure.rs
- src/transform.rs
- src/vector.rs
Closes #344
This will allow us to move forward on #337
> Integrate One and Zero traits into the algebraic trait heirachy

- src/matrix.rs
All are duplicates of the same functions for Matrix3, with extra parameters added in to make up the full 4x4.
These are in response to #324
> implement from_angle{x, y, z} and from_axis_angle for Matrix4

- src/lib.rs
- src/rotation.rs
- src/structure.rs
- src/transform.rs
- tests/matrix.rs
As discussed in https://github.com/bjz/cgmath/pull/347#issuecomment-218015938
> Remove invert self methods

- src/angle.rs
- src/projection.rs
- src/quaternion.rs
> Remove unused imports

- src/transform.rs
> Remove AffineMatrix3

- src/angle.rs
- src/euler.rs
- src/lib.rs
- src/rotation.rs
- src/structure.rs
- tests/angle.rs
- tests/matrix.rs
- tests/quaternion.rs
- tests/rotation.rs
- tests/vector.rs
Updated https://github.com/brendanzab/cgmath/pull/341 to the newest commit.
> Moved angle types to tuple structs

- src/euler.rs
- src/quaternion.rs
- src/rotation.rs
- src/vector.rs
I’ll add more commits as I read through the documentation if I find any others.
> Fixed documentation typo(s)

- CHANGELOG.md
- Cargo.toml
- src/transform.rs
- Update `serde`, `serde_derive`, and `serde_json` to version `1.0`.
Closes #404 
CC @brendanzab
> Update serialization to serde v1.0

- src/matrix.rs
- src/quaternion.rs
- src/rotation.rs
- src/structure.rs
- src/vector.rs
- tests/matrix.rs
- tests/quaternion.rs
- tests/vector.rs
This allows one to easily sum up a sequence of vectors or matrices.
> iter traits: impl `iter::{Sum, Product}`

- src/matrix.rs
Closes #210 
Sorry for the lateness on this one.
I just went with @tomaka's fix in the end: https://github.com/brendanzab/cgmath/issues/210#issuecomment-269957016
> Fix matrix inversions for small determinants

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- src/angle.rs
- src/euler.rs
- src/lib.rs
- src/macros.rs
- src/matrix.rs
- src/point.rs
- src/projection.rs
- src/quaternion.rs
- src/rotation.rs
- src/transform.rs
- src/vector.rs
- tests/transform.rs
- tests/vector4f32.rs
r? @brendanzab 
Note: breaking change
> Features refactor

- src/structure.rs
- tests/vector.rs
Adds a project method to InnerSpace.
IMPORTANT NOTE: I did not check to see if this compiles because I am a bad person :(
I thought I should ask before doing that, should a test be added for this? The correctness of this method somewhat relies on dot and magnitude2 being correct.
> Added project_on to InnerSpace

- src/vector.rs
Probably the smallest PR I've ever done, but it bothered me.
> Fix docs for unit_z on Vector3

- src/matrix.rs
- src/point.rs
- src/quaternion.rs
- src/structure.rs
- src/vector.rs
This method is useful in debug to error early when some kind of singularity is encountered.
> Add is_finite method to vectors and matrices.

- src/euler.rs
- src/matrix.rs
- src/point.rs
- src/quaternion.rs
- src/vector.rs
This makes it easier to create vectors in constants.
> Declare vector constructors to be const

- src/lib.rs
Grammatical change from singular to plural.
> fixed dropped 's' in trait.

- benches/common/macros.rs
- benches/construction.rs
- benches/mat.rs
- benches/quat.rs
- benches/vec.rs
- build.rs
- src/angle.rs
- src/euler.rs
- src/lib.rs
- src/macros.rs
- src/matrix.rs
- src/num.rs
- src/projection.rs
- src/quaternion.rs
- src/quaternion_simd.rs
- src/rotation.rs
- src/structure.rs
- src/transform.rs
- src/vector.rs
- src/vector_simd.rs
- tests/matrix.rs
- tests/quaternion.rs
- tests/transform.rs
- tests/vector.rs
- tests/vector4f32.rs
The reason of this PR is because I need to transform thing in a 2d plane, and these functions are really handy.
- Added to the Mat3 the possibility to be constructed from a translation vector, similarly to the Mat4.
- Added unit tests.
> Mat3 constructors enhancement

- src/euler.rs
- src/matrix.rs
- src/quaternion.rs
- src/quaternion_simd.rs
- src/vector_simd.rs
Followup of #528, I did a more thorough search and found some that I missed.
> More Into impls converted to From
