src/cgmath.rs, src/vector.rs, tests/vector.rs
Fixes #162 
I figured that quaternions and points don't need those really. No one just writes quaternions as raw numbers, you typically use axis/angle notation for constructing them. As for the points - I'm yet to see examples where you need anything but zero.
=> Implemented short vector constructors

src/cgmath.rs
Fixes compile error. `#[plugin] extern crate rand_macros;` is deprecated now.
=> Rust version up

src/transform.rs, tests/transform.rs
The new design avoids `Rotation` associated type, because it was impossible to restrict it better for more defined `ToComponents2` and `ToComponents3`.
Also found out that `ToComponents` implementation for `AffineMatrix3` was not correct. Removed it until I'm able to get a proper one.
=> Redesigned ToComponents to avoid the associated type

src/lib.rs, src/line.rs, src/ray.rs, src/rotation.rs, src/transform.rs
This is a _huge_ kludge to limp a little further with this library before someone actually migrates it to Associated types.
=> Remove old_impl_check

src/angle.rs, src/matrix.rs, src/projection.rs, src/quaternion.rs, src/rotation.rs, src/transform.rs, tests/angle.rs, tests/quaternion.rs, tests/rotation.rs
=> Replace most To* traits by Into

src/matrix.rs, src/projection.rs, src/rotation.rs, src/transform.rs
[RFC 1214](https://github.com/rust-lang/rfcs/blob/master/text/1214-projections-lifetimes-and-wf.md) fixed some bugs / incorrect behaviour in `rustc` which requires additional bounds in some places.
=> fix rfc 1214 fallout

src/array.rs, src/matrix.rs, src/point.rs, src/quaternion.rs, src/vector.rs
Fixes #225
Closes #222
This is a breaking change and will probably require a version bump. I would like to do other things before this happens though, like removing all the operator methods in favor of implementing the operator traits.
=> Remove FixedArray trait in favour of std::convert

src/matrix.rs
Now we can call them like `Matrix4::identity()`! Yay!
This also adds `Matrix::from_diagonal`, which probably closes #217.
=> Move some methods onto the Matrix trait

src/array.rs, src/matrix.rs, src/point.rs, src/quaternion.rs, src/vector.rs, tests/vector.rs
This doesn't seem to be used anywhere - not sure how useful it is. It isn't really a proper `map` anyway, because it mutates `self`.
=> Remove {Array1, Array2}::map method

src/aabb.rs, src/matrix.rs, src/point.rs, src/quaternion.rs, src/transform.rs, src/vector.rs, tests/matrix.rs
We can't yet remove the ugly operator methods, due to rust-lang/rust#20671
This also removes the implementations of `Zero` and `One` for vectors, and removes the by-value operator implementations.
=> Implement binary operators for points, vectors, quaternions, and matrices

src/angle.rs, src/approx.rs, src/array.rs, src/matrix.rs, src/num.rs, src/point.rs, src/quaternion.rs, src/rotation.rs, src/transform.rs, src/vector.rs, tests/transform.rs
rust-lang/rust#24092 has caused quite a bit of ugliness, but I've tried to work around it as best I can.
=> Convert trait type parameters to associated types

src/matrix.rs
Uniform scale matrices are probably the more common case. It probably makes sense that this has the shorter constructor.
=> Rename matrix scale functions for better ergonomics

CHANGELOG.md, src/quaternion.rs
=> Add missing by-ref and by-val permutations of quaternion operators

CHANGELOG.md, src/lib.rs, src/macros.rs, src/point.rs, src/quaternion.rs, src/vector.rs
This moves lots of the common code generation patterns into a macros module. In doing so, the code can be greatly reduced in size.
I also removed some redundant component-wise functions that I found on `Point` that are now covered by `Array`.
=> Standardise macro use for code generation

CHANGELOG.md, src/matrix.rs, src/point.rs, src/quaternion.rs, src/transform.rs, src/vector.rs, tests/projection.rs, tests/vector.rs
- Removes the operator methods from `Vector` and `Point` traits #267
- Removes `*_self` methods from `Vector`and `Point` traits
- Removes `Vector::one` #270
=> Operator method sweep

src/matrix.rs, tests/matrix.rs
I was getting some strange behavior when converting from a Basis3 into a Quaternion so I looked into the conversion implementation. I noticed the implementation differed slightly from the link in the function (http://www.cs.ucr.edu/~vbz/resources/quatut.pdf on page 8). I think I changed it to match the implementation in the pdf, but confirmation that things are matching now would be great. I also added a test which fails with the previous implementation and passes with these changes.
Let me know if anything is broken or anything you would like changed/improved.
=> Fix conversion from Matrix3 to Quaternion

src/macros.rs, src/point.rs, src/quaternion.rs, src/vector.rs, tests/point.rs, tests/quaternion.rs, tests/vector.rs
This change adds support for scalars on the left hand side of arithmetic operators, so far just for VectorN types.
In cgmath you could write code like ```Vector3::unit_y() * 2.0``` but not ```2.0 * Vector3::unit_y()```. This change adds support for the latter.
To do this, I had to add trait support for each built in numeric type. I've done this using macros, trying to keep the style close to what was already there. I noticed for the Vector operators there are also operators that take a reference, I'm not sure if I need to provide those or not?
I've also added a few tests for operators. I've used a macro to cut down on duplicate code, the down side being when it fails it's a pain to work out which line failed.
=> Support for scalar on the lhs of arithmetic operators

src/vector.rs
Docs state EuclideanVector trait is only implemented for 2d and 3d vectors, but there does appear to be a Vector4 implementation. 
Added that it's only implemented for float types, since I didn't realise that initially.
=> Small doc fix for EuclideanVector trait

CHANGELOG.md, src/angle.rs, tests/angle.rs
Removes `Angle::equiv`, and moves `Angle::new` to be implemented directly on angle types. Also updates some of the angle documentation.
=> Angle updates

CHANGELOG.md, src/array.rs, src/matrix.rs, src/point.rs, src/rotation.rs, src/vector.rs, tests/vector.rs
The `Vector` and `EuclideanVector` traits roughly line up with the concept of vector spaces and inner spaces respectively. It makes more sense to group `dot` with the other methods that depend on it.
I've also added a default implementation of `angle`. Now the only required method for `EuclideanVector` is `dot`.
The `neg_self` methods are kind of weird... they aren't associated with any traits. I think they were left-over from before we moved to operator impls. If we want to had a more reasoned approach to how we do in-place operations, I'm open to it, but I think that should be talked about somewhere else.
`Vector::from_value` has been moved to `Array`, seeing as it is more of an 'array-ish' thing.
=> Vector API cleanups

src/array.rs, src/macros.rs, src/matrix.rs, src/num.rs, src/vector.rs
Assignment operators were stabilised in Rust 1.8.
=> Stabilise assignment operators

README.md
"paramerise" -> "parameterize", and "more than useful" -> "more than enough" (which is better wording in the context I think).
=> Fix typo and wording in README

src/matrix.rs, src/transform.rs, tests/transform.rs
Pursuant to conversations in #337, #302, and #324, I've implemented Transform for these two matrices. This makes working with the matrices as fully-fledged transformations much easier.
Along the lines of https://github.com/bjz/cgmath/pull/302#issuecomment-211168768, I've also implemented Transform2 and Transform3 for Matrix3, to reflect its potential use as both a 3D rotation matrix and a 2D affine transform.
Transform3 is implemented for Matrix4 as well, and I moved the From<Euler> impls down with the rest of the From impls, in an unrelated edit which I think nonetheless improves readability of what is now a rather large file.
I'm not positive I've gotten the Transform2 implementation for Matrix3 correct, would appreciate a sanity check :D
=> implement Transform for Matrix3 and Matrix4

src/lib.rs
I'm not sure whether we should continue to depend on the `num_traits` crate, but at least this makes it easier for clients of cgmath to access the traits from the crate, rather than having to add `num_traits` to their own `Cargo.toml`.
=> Re-export num-traits crate

.travis.yml, Cargo.toml, src/angle.rs, src/euler.rs, src/lib.rs, src/matrix.rs, src/point.rs, src/projection.rs, src/quaternion.rs, src/rotation.rs, src/transform.rs, src/vector.rs, tests/transform.rs
There is a few things to note:
- I made `rustc-serialize` dependency optional to allow choosing between the two crates.
- Serde macros does not seem to support associated types. I had to implement the trait manually for `Decomposed`
- I did not use `syntex` for stable rust support as I was unsure how to handle the build configuration with both `serde_macros` and `serde_codegen` as optional dependencies.
Closes #313
=> Adds nightly serde support

CHANGELOG.md, src/euler.rs, src/matrix.rs, src/quaternion.rs, src/rotation.rs, tests/matrix.rs, tests/quaternion.rs
Fixes #285 and maybe #143.
I just started learning 3D graphics and ran into #285, but since I have some past experience with Euler angles and quaternions, I tried fixing it.
I started by adding tests. These tests used to fail and now pass:
- rotate_from_euler::test_x
- rotate_from_euler::test_z
- rotate_from_euler::test_y_then_z
- matrix3::rotate_from_euler::test_x_then_y
- matrix3::rotate_from_euler::test_y_then_z
I'm pretty sure the equations in #290 are wrong because Euclidean Space uses YXZ Euler angles, but cgmath is using XYZ. Reordering the angles does not give the right answer (and since axis angle to quaternion conversion currently works correctly, the hack to fix axis angles is incorrect and an indication the other equations are wrong). This NASA document gives equations for all …
=> Rotation fixes

CHANGELOG.md, Cargo.toml
Sorry for the lateness :(
I decided just to keep in the updates that make `Rotation` inherit `One`. Future work will be needed to fully overhaul the transformation API though.
=> Bump version to v0.10.0

src/matrix.rs, src/quaternion.rs, src/rotation.rs, tests/matrix.rs, tests/quaternion.rs, tests/rotation.rs
This normalizes the use of `Rad<S>` to the same as the `perspective` function.
=> Made uses of Rad<S> more generic using Into<Rad<S>>

src/angle.rs, src/euler.rs, src/matrix.rs, src/point.rs, src/quaternion.rs, src/vector.rs
This is intended as a partial fix for #375. It doesn't also remove #[repr(C)],
since it's a bit unclear whether that's necessary.
=> Removes #[repr(packed)] from all structs where it was specified.

src/matrix.rs, src/point.rs, tests/matrix.rs, tests/point.rs
This fixes #380 by directly implementing these functions for these types, in the same way they were already implemented for the `Vector` type. This also adds tests to test the new features.
=> Implement component wise number casting for the Point and Matrix types.

Cargo.toml, src/lib.rs
It looks like serde_macros was removed in serde 0.8.11 - https://github.com/serde-rs/serde/commit/1b6fd5a362ae1925153213ab329678a4ce2e2ce4.
=> Use serde_derive instead of serde_macros.

.travis.yml, Cargo.toml, src/transform.rs
Use Serde 0.9 that no longer requires the usage of Nightly. Fixes #398.
Also adds a test run for `--features eders` to Travis config.
=> Bump to serde 0.9

src/quaternion.rs, tests/quaternion.rs
Quaternion::between_vectors does not work for vectors in opposite directions.
The source code references a stackoverflow answer, but there is another answer which does take into account opposite vectors: http://stackoverflow.com/a/11741520/2074937. This PR is an implementation of that answer.
=> Fix between_vectors for opposite vectors

Cargo.toml, src/angle.rs, src/euler.rs, src/lib.rs, src/matrix.rs, src/point.rs, src/projection.rs, src/quaternion.rs, src/rotation.rs, src/transform.rs, src/vector.rs
According to [Rust release milestone predictions](https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591?u=dtolnay), rustc-serialize is scheduled to be deprecated in next month's beta release of Rust.
Closes #395
=> Drop rustc-serialize support

src/angle.rs, src/matrix.rs, src/quaternion.rs, src/rotation.rs, src/structure.rs, src/vector.rs, tests/angle.rs, tests/matrix.rs, tests/quaternion.rs, tests/vector.rs, tests/vector4f32.rs
This continues on from #406
I cleaned up the impls to be consistent with the other code in cgmath, and implemented `Sum` for `Angle`s. I also reordered the assertions so that type inference worked, and ensured that the tests covered both taking the iterator items by value _and_ by ref.
=> Sum and Product cleanups

src/matrix.rs, src/quaternion.rs, src/rotation.rs
Replace all `impl .. for Struct<<A as Angle>::Unitless>` by `Struct<A::Unitless>`. 
This allows `-Zsave-analysis` to work, and I think this is more readable too.
=> Workaround rust-lang/rust#41478.

src/num.rs, src/point.rs, src/structure.rs, src/vector.rs, tests/vector.rs, tests/vector4f32.rs
Closes #396
This removes `PartialOrd` and makes `BaseNum` and `BaseFloat` simple trait aliases. This should allow more types to be used as parameters in the cgmath data types at the expense of removing `Array::min` and `Array::max`.
=> Remove PartialOrd

src/quaternion.rs, tests/quaternion.rs
I'm not sure if the doc comment is correct (I just copied it from the vector method).
=> Add cast method to Quaternion

.travis.yml, CHANGELOG.md, Cargo.toml, src/angle.rs, src/euler.rs, src/lib.rs, src/macros.rs, src/matrix.rs, src/point.rs, src/projection.rs, src/quaternion.rs, src/rotation.rs, src/transform.rs, src/vector.rs, tests/transform.rs, tests/vector4f32.rs
Includes #417
r? @brendanzab 
Notice how matrix and Euler conversions have stronger types (to `ColumnMatrix*<>` and `EulerAngles<, IntraXYZ>` respectively).
=> Mint flavour integration

src/point.rs, src/structure.rs, src/vector.rs
This is to allow functions to use Index, IndexMut, etc. generically over different length vectors
possible changes:
- bikeshedding the name
- put it on its own trait
=> added len function to Array

Cargo.toml
old version of cocoa wasn't building on nightly (it's a dependency of glium->glutin->cocoa and glium->glutin->winit->cocoa on osx)
updating glium fixes it
=> update glium to version 0.17

src/angle.rs, src/point.rs, src/structure.rs, src/vector.rs
Implements [`Bounded`](http://rust-num.github.io/num/num_traits/bounds/trait.Bounded.html) for all Points, Vectors, and Angles where `S` also implements `Bounded`, giving `min_value` and `max_value` functions.
Should `Bounded` be re-exported from the crate root? This PR currently doesn't, but other `num_traits` traits are exported from `cgmath`'s root
=> Implement num_traits::Bounded for Points, Vectors, and Angles

src/matrix.rs, src/point.rs, src/quaternion.rs, src/vector.rs, tests/matrix.rs, tests/point.rs, tests/quaternion.rs, tests/vector.rs, tests/vector4f32.rs
Right now, the `cast()` functions simply panic when a cast fails, crashing the entire program unhandleably (ignoring panic hooks). This PR makes said functions return `Option<_>`, so that a program may catch and handle failed casts. Unfortunately this is a breaking change, but programs should be able to handle a failed cast which can reasonably happen even within properly-implemented code.
=> Modify cast functions to return Option

src/transform.rs, tests/transform.rs
This is heavily used in collision detection. It's much cheaper to do the inverse transform of a ray/support function direction vector/etc, than to transform all the vertices of a primitive/complex shape.
We've found ourselves writing: `transform.inverse_transform().and_then(|inverse| Some(inverse.transform_vector(some_vec)))` over and over, so we felt there was a solid use case for having this in cgmath. It is also something that specific implementations of the Transform trait can do a much better version of than doing the full inverse of the transform, since vector space has no concept of translation.
=> Adding inverse transformation of a vector to the Transform trait.

Cargo.toml, README.md, build.rs, src/macros.rs, src/point.rs, src/vector.rs, tests/swizzle.rs
Implements #429.
I extended the swizzle operators I originally proposed to a more complete set allowing repeating variables as well as making larger vectors from smaller ones. This PR effectively makes creating new vectors from old ones as simple and terse as calling `abcd()` on a point or vector where `a`,`b`,`c`, and `d` are one (or none) of the variables available in the original point or vector. For example if we have
```rust
let v = Vector3::new(1.0, 2.0, 3.0);
```
then `v.xyxz()` produces a
```rust 
Vector4 { x: 1.0, y: 2.0, z: 1.0, w: 3.0 }
```
and `v.zy()` produces a 
```rust 
Vector2 { x: 3.0, y: 2.0 }
```
Instead of hardcoding all the operators I added a build.rs script that effectively generates a `swizzle_operator_macro.rs` file in the output directory, which is then included …
=> Swizzle Operators

src/point.rs, src/structure.rs
`PointN` implements `Add<VectorN>`, so it seems natural that `Sub<VectorN>` should be implemented as well.
=> Add vector subtraction for all points

src/point.rs
Adds element-wise functions to `Point` types. Makes sense to implement because `ElementWise` exists for mainly for pragmatic reasons, and there are cases where doing element-wise operations on `Point`s makes sense.
=> Implement ElementWise for PointN

src/point.rs, src/vector.rs
These are similar to the `map` function on the `Option` type, but perform the function on every scalar in the point or vector and put the result into a new point or vector of the same dimension. This would be useful for performing more complex element-wise operations than the ones found in the `ElementWise` trait, although unfortunately I can't see a way to implement it in that trait without having associated type constructors.
=> Add map functions to points and vectors

Cargo.toml, benches/common/macros.rs, benches/construction.rs, benches/mat.rs, benches/quat.rs, benches/vec.rs, src/angle.rs, src/euler.rs, src/matrix.rs, src/quaternion.rs, src/vector.rs
Rand 0.5 has a couple of warnings and breaking changes:
`Rand` is deprecated and replaced with a Distribution construction:
```rust
impl<S: BaseFloat + SampleRange> Rand for $Angle<S> {
#[inline]
fn rand<R: Rng>(rng: &mut R) -> $Angle<S> {
$Angle(rng.gen_range(cast(-$hi).unwrap(), cast($hi).unwrap()))
}
}
```
becomes
```rust
impl<S> Distribution<$Angle<S>> for Standard 
where Standard: Distribution<S>,
S: BaseFloat + SampleUniform {
#[inline]
fn sample<R: Rng + ?Sized>(&self, rng: &mut R) -> $Angle<S> {
$Angle(rng.gen_range(cast(-$hi).unwrap(), cast($hi).unwrap()))
}
}
```
`IsaacRng::new_unseeded` is deprecated, and rand recommends using [FromEntropy](https://docs.rs/rand/0.5.0/rand/trait.FromEntropy.html). Other options are (from rand's docs):
- Deterministic creation using …
=> Bumped rand to 0.5

src/projection.rs
Those links were broken before, since the [] and () part were split
into two different lines. This also caused warnings on nightly, which
are now fixed.
=> Fix links to OpenGL API in docs

CHANGELOG.md, src/structure.rs
Because it does not require dot product.
Along the way, fix the comment.
Fixes #471.
=> [breaking] Move lerp() from InnerSpace to VectorSpace

src/structure.rs, tests/angle.rs
This method is like `normalize` except that it normalizes to have an
absolute value of no more than `turn_div_2`.
---
This is useful for making sure that an angle is no more than some offset from a target angle (e.g., implementing maximum turn rates in games).
=> Angle: add the normalize_zero method

.travis.yml, Cargo.toml, README.md
This is unfortunate, but it appears that we need to move to the new SIMD API in order to unblock it.
=> Readme links update, let travis fail on nightly

src/lib.rs, src/point.rs, src/vector.rs, tests/point.rs, tests/vector.rs
In my code I find that I need to create points almost as often as vectors, so having short constructors is helpful.
=> Add short constructors for points, to match the ones for vectors

src/quaternion.rs
Clarifies that a quaternion should be normalized to be used as a rotation. Does not enforce or assert that the quaternion is normalized because valid rotations can be slightly off of the unit quaternion due to floating point error.
Fixes #479.
=> Add documentation for `<Quaternion as Rotation<Point3<S>>>::rotate_vector`

.travis.yml, Cargo.toml, src/angle.rs, src/euler.rs, src/lib.rs, src/matrix.rs, src/quaternion.rs, src/vector.rs
Closes #481 
This PR leaves the feature enabled by default so that this can be released as a minor version soon. (I would suggest to disable it by default in future versions, but that's another discussion.)
The changes are pretty straight forward with one catch: I changed some `use` statements to nested imports (otherwise, there would be even more `#[cfg(feature = "rand")]` lines). Nested imports were stabilized in 1.25 (see [the edition guide on this feature](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/nested-imports-with-use.html)). I'm not sure how cgmaths policy on minimum compiler version is. Maybe cgmath already requires a >= 1.25 compiler for other reasons. If my change is a problem, just tell me and I will change the imports back.
=> Make `rand` dependency optional (but enabled by default)

CHANGELOG.md, src/point.rs, src/vector.rs
Implements #485. 
It is possible but messy to put `map` and `zip` in the Array trait. Rust doesn't support higher kinded types which would help because we want to abstract over any container, holding a fixed number of some item type. The implementation would basically need to reproduce the work in the generic-array crate which is silly.
=> Implement zip for VectorN and PointN

Cargo.toml, tests/matrix.rs, tests/point.rs, tests/quaternion.rs, tests/transform.rs, tests/vector.rs, tests/vector4f32.rs
Would it be possible to get a new release published? Rand is still a default feature in the published version.
=> bump rand -> 0.7, fix unused macro warnings in tests

src/matrix.rs, src/rotation.rs, tests/matrix.rs
1. Fixes `Matrix2::look_at`
2. Adds tests for `look_at`
3. Adds a new function, `look_at_stable`
I added a new function for 2d look at rotation. `look_at` is a bit weird in practice for 2d. For example, if you are making a basis matrix to orient a 2d character to look at a point, `look_at` will flip the character as they rotate past `up` or `-up` vectors. This is the best match for what look_at is supposed to do, I think.
`look_at_stable` will not flip based on orientation, you just pass in which way to flip. This is a bit easier to use to rotate 2d characters.
`look_at_stable` could have a better name. I think we can also consider removing the flip param, and just let the user flip the matrix with a transform later.
=> Fix Matrix2::look_at, add look_at_stable

src/point.rs, src/structure.rs, src/vector.rs
This PR makes a step towards finer grained trait bounds (#496)
Here I just relaxed the `BaseFloat` trait bounds into `num_traits::Float` on `InnerSpace`, `MetricSpace` and `is_finite`, and added the required bounds from `approx` to the functions that need it.
This is helpful because it allows the use of common functions like `magnitude` without having to implement the `approx` traits on the number type.
=> Relax BaseFloat bounds

Cargo.toml, benches/common/macros.rs, benches/construction.rs, benches/mat.rs, benches/quat.rs, benches/vec.rs
This adds the `rand_isaac` dependency since that's no longer in the `rand` crate, but in the future we should consider switching to an RNG in `rand` so we don't need another dependency.
=> Fix compilation of benchmarks

src/projection.rs
While trying to make an inverted depth using a floating-point depth buffer. I got a panic from the asserts! macro preventing such behaviour. 
I have removed such macros to allow for a higher accuracy inverted depth fp32 buffer. 
Here below a render doc screenshot of it working:
Tests still pass accordingly. 
I did not find any particular guideline on the contribution or how the PR should be formatted, so I hope this is good enough.
=> Allow inverted near far for inverted depth fp32

benches/construction.rs, benches/mat.rs, benches/quat.rs, benches/vec.rs, src/matrix.rs, src/point.rs, src/quaternion.rs, src/rotation.rs, src/structure.rs, src/transform.rs, src/vector.rs, tests/rotation.rs, tests/transform.rs
This fixes the `multiple one found` issue (one function mentioned in #354) with attempting to use `Matrix4::one()` or some other matrix's `one()` function when importing the prelude, which includes both `Transform` and `One`. The changes:
- `Transform::one()` is gone
- `Transform` is now a subtrait of `One`
- `Decomposed` implements `One`.
- `EuclideanRotation` is a new trait specifically for implementers of `Rotation<P>` for exactly one `P`. This allows `Decomposed` to implement `One` without running into unconstrained type parameter issues. All current implementers of `Rotation` in the `cgmath` crate implement `EuclideanRotation`.
- `Decomposed` implements `Mul` so it can implement `One`.
I know there was an attempt to do it in #386, but it was abandoned and closed.
There seems to be a …
=> Now there is only one one

benches/construction.rs
`Rotation3`’s type argument is an associated type now. Therefore this line https://github.com/rustgd/cgmath/blob/84da664455df0ec6d7583131e985ffd3a184a2f4/benches/construction.rs#L32 will cause following error when running `cargo bench`.
```
error[E0107]: wrong number of type arguments: expected 0, found 1
--> benches/construction.rs:32:39
|
32 | fn bench_from_axis_angle<T: Rotation3<f32>>(bh: &mut Bencher) {
|                                       ^^^ unexpected type argument
error: aborting due to previous error
```
This PR is intended to fix this.
- - - - -
My environments:
* Rust v1.48.0-nightly
* macOS
=> Fix a type argument in benchmarks

CHANGELOG.md, src/quaternion.rs
The `From` and `Into` impls for `[S; 4]` and `(S, S, S, S)` have been changed accordingly. This is consistent with other libraries like glm, nalgebra, and glam, as well as the glTF spec.
Note that the `Quaternion::new` constructor has not yet been updated.
Related: https://github.com/rustgd/cgmath/issues/499
@kvark I hadn't previously thought much about the From/Into conversions for `[S; 4]` and `(S, S, S, S)`. It makes me a little nervous since this change is going to break safe code. We should probably also update the `Quaternion::new` constructor but I wanted to see if there was any feedback first.
=> Quaternion memory layout changed to `[x, y, z, w]`

src/matrix.rs, src/transform.rs, tests/matrix.rs, tests/transform.rs
The corresponding functions have been added to Matrix4 and Decomposed and are now consistent.
Matrix3, Matrix2, and the Rotation trait are only partially updated. The `look_at` methods on these should probably be renamed to `look_to_[lh|rh]` as they take a direction vector, not a focus point. Does handedness even make sense for Matrix2?
The older functions have all been left in-tact and marked deprecated. I don't think the old functionality should be removed in the near or medium term.
=> Add Transform::{look_at_rh, look_at_lh} and deprecate look_at

Cargo.toml, README.md
Closes #499
r? @aloucks  (check the invites on github and crates)
=> Release 0.18

src/macros.rs
Fixes missing impls of `impl From<ArrayN> for ForeignType` which is currently provided as `impl Into<ForeignType> for ArrayN`
From the [`std::convert::Into` documentation](https://doc.rust-lang.org/stable/std/convert/trait.Into.html):
> One should avoid implementing Into and implement From instead. Implementing From automatically provides one with an implementation of Into thanks to the blanket implementation in the standard library.
While it isn't very significant, as you can write `cgmath_vector.into()` in most places, it makes code cleaner where type inference is not possible (e.g. `format!` macros):
```rust
// With `Into`: 
<Vector2<f32> as Into<[f32; 2]>>::into(a_vector)
// ... versus with `From`:
<[f32; 2]>::from(a_vector)
```
(Example adapted from this [real code …
=> Implement From instead of Into for array/tuple/mint conversions

Cargo.toml
Hi.
I am in the process of packaging ``cgmath`` in fedora and it would ease the process to update ``approx`` to 0.5.
Thanks for your time.
=> update approx to 0.5

src/quaternion.rs
The old link no longer goes to a valid page, and it appears to be malicious.
=> Update links in quaternions.rs

src/angle.rs, src/matrix.rs, src/num.rs, src/point.rs, src/quaternion.rs, src/rotation.rs, src/structure.rs, src/vector.rs
The first commit removes the NumCast from the BaseNum trait. This is enough to allow using non-machine scalars (e.g. fixed precision numbers) for vector/point operations:
```
#![feature(array_map)]
use cgmath::InnerSpace;
use fixed::types::I16F16 as Ftype;
macro_rules! show {
($e:expr) => {
println!("{}: {:?}", stringify!($e), $e);
};
}
fn main() {
let p1: cgmath::Point2<Ftype> = [0, 1].map(Ftype::from_num).into();
show!(p1);
let p2: cgmath::Point2<Ftype> = [1, 0].map(Ftype::from_num).into();
show!(p2);
show!(p2 - p1);
let v: cgmath::Vector2<Ftype> = [1, 1].map(Ftype::from_num).into();
show!(v);
show!(p1 + v);
show!(v.magnitude2());
show!(v.dot(v));
}
```
- `cast` is already parameterized by `T: NumCast`
- The `midpoint` method used cast to create a generic value of '2', but this can be …
=> Remove NumCast from BaseNum and relax float bounds

Cargo.toml, src/macros.rs, src/matrix.rs, src/quaternion.rs
Mint 0.5.8 added a new trait called [IntoMint](https://docs.rs/mint/0.5.8/mint/trait.IntoMint.html), which lets you specify the mint type that another type is associated with. That way you can convert a type into its mint representation without having to specify the mint type.
I implemented IntoMint for Vectors, Points, Matrices, and Quaternions.
I didn't implement IntoMint for Euler angles, because I couldn't figure out which mint type they should correspond to.
=> Implement IntoMint trait for Vectors, Points, Matrices, and Quaternions

Cargo.toml, src/euler.rs, src/lib.rs, src/macros.rs, src/matrix.rs, src/point.rs, src/quaternion.rs, src/structure.rs, src/vector.rs
Added support for [bytemuck](https://docs.rs/bytemuck) crate.
I also applied `cargo fmt`, but I think it is out of scope, so I can remove that changes if you mind.
=> Add support for cast using bytemuck crate

README.md, src/projection.rs
This adds a new type, `PlanarFOV`, and a new function `planar` to create a projection matrix for which the view space is projected to a plane at zero depth, currently two units high. This allows the focal point to move freely according to the specified vertical field of view, making for a continuous transition from positive FOV to zero or even negative FOV.
I'm unsure of using the name `PlanarFOV` for this, which was derived from how it keeps a plane's transformation fixed as the FOV is adjusted. Additionally, it may be appropriate to add a height parameter to customize the height of the fixed plane instead of fixing it to extend one unit in each direction.
If desired, I can add some test cases to verify the boundary constraints that this projection was derived from.
=> Planar projection (perspective/orthographic combination projection)

src/projection.rs
The planar projection math from #556 had an error in how the focal point was calculated, where it assumed the height was equal to `2.0`. This fixes that by adding height as a parameter to that expression.
=> Fix planar projection focal calculation
